### ISSUE TITLE
Replace missing floor tiles behind toilet

### ISSUE THREAD

**Issue by jcushman** [jcushman/house#59]
* [ ] find matching tiles??

**Comment by jcushman** [comment]
Tiles look like this:

![2015-09-07 18 39 27](https://cloud.githubusercontent.com/assets/376272/9723591/61e557e2-5592-11e5-9cc4-929b6776a406.jpg)

Floor looks like this:

![2015-09-07 18 39 40](https://cloud.githubusercontent.com/assets/376272/9723594/68e7cffc-5592-11e5-9c5c-db9196e0ebbc.jpg)

**Comment by teresaORM** [comment]
Are you my bathroom tile?


![tile](https://cloud.githubusercontent.com/assets/1180804/12623202/10531336-c4f7-11e5-969d-60295fad1672.jpg)


http://www.homedepot.com/p/Merola-Tile-University-Blue-11-3-4-in-x-11-3-4-in-x-5-mm-Porcelain-Mosaic-Floor-and-Wall-Tile-9-62-sq-ft-case-FKOUV418/203784071
http://retrorenovation.com/2012/11/01/bathroom-floor-tile-in-production-since-the-1970s-merola-university-random-mosaic/

But how can I buy less than 10 sq feet?

**Comment by jcushman** [comment]
Wow! Amaze!

Maybe we could get these guys to send us a sample?
http://somertile.com/ProductDetail/S1FKOUV418_university-Blue

**Comment by teresaORM** [comment]
Is this the same site? They will send samples for $14.95 shipping, but I'm not sure how big the piece is.
http://merola.somertile.com/productCatalog.aspx

Or wait, you can buy this at home despot by the square foot. Close enough?

![tiles2](https://cloud.githubusercontent.com/assets/1180804/12630639/660d9f66-c51b-11e5-9303-957388701e2e.jpg)

http://www.homedepot.com/p/Merola-Tile-Academy-Blue-11-3-4-in-x-11-3-4-in-x-5-mm-Porcelain-Mosaic-Tile-FKOTMR18/205789433?MERCH=RV-_-OD_gm_pip_rr-_-203784071-_-205789433-_-N

**Comment by teresaORM** [comment]
Patched!
![image](https://cloud.githubusercontent.com/assets/1180804/12869258/105a9c7a-cce8-11e5-9df5-035054797f36.jpeg)
